[package]
name = "zanderlewis"
version = "0.0.1"
edition = "2021"
authors = ["Zander Lewis <zander@zanderlewis.dev>"]
repository = "https://github.com/zanderlewis/zanderlewis-card"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.28"

